/*
 * This source file was generated by the Gradle 'init' task
 */
package ru.bsu.cad.lab;

import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import ru.bsu.cad.lab.config.AppConfig;
import ru.bsu.cad.lab.renderer.Renderer;

public class App {
    public static void main(String[] args) {
        AnnotationConfigApplicationContext context = new AnnotationConfigApplicationContext(AppConfig.class);
        Renderer renderer = context.getBean(Renderer.class);
        renderer.render();
        context.close();
    }
}
